### ISSUE TITLE
GTK3 version lacks vertical lines/delimiters for columns; Uses weird icons

### ISSUE THREAD

**Issue by birdie-github** [audacious-media-player/audacious#1374]
1. Where have all the delimiters gone?

GTK2 4.3.1:

![gtk2](https://github.com/audacious-media-player/audacious/assets/4958603/68bf35a1-c79f-4ab4-966b-6fa7093a1036)

GTK3 4.4.0-beta1:

![gtk3](https://github.com/audacious-media-player/audacious/assets/4958603/64865f0f-33d0-412e-9f41-c007591ba176)

2. How can I get "normal" icons back?

**Comment by radioactiveman** [comment]
1. Whether delimiters are shown is not affected by Audacious. Report this to the developers of your theme. What theme is that by the way?
2. Settings -> Appearance -> Miscellaneous -> Use symbolic icons in toolbar

**Comment by birdie-github** [comment]
1.

> What theme is that by the way?

The same theme for GTK2/GTK: Greybird.
```
rpm -qa | grep grey
greybird-dark-theme-3.23.1-7.fc40.noarch
greybird-light-theme-3.23.1-7.fc40.noarch
```

https://github.com/shimmerproject/Greybird

It's weird it behaves differently as a GTK3 theme, than as a GTK2 theme. Should I create a bug report with them?

2. Thanks a lot! That has fixed it.

**Comment by radioactiveman** [comment]
> It's weird it behaves differently as a GTK3 theme, than as a GTK2 theme. Should I create a bug report with them?

Yes, please do that. We can't solve this in Audacious, therefore closing.
