### ISSUE TITLE
OPUS - embedded cover art in METADATA_BLOCK_PICTURE fails to be parsed

### ISSUE THREAD

**Issue by hlinden** [audacious-media-player/audacious#1387]
I have used a "real world" audio sample for this bugreport in order to make the results, including fingerprinting and tagging in Musicbrainz Picard reproducable.

The attached audio sample is from this release: https://archive.org/details/BSOG0006/01-TheBurnsWeEarn_192kb.mp3

The license looks okay for the purpose of attaching it to a bugreport.

This is the corresponding album on musicbrainz: https://musicbrainz.org/release/c652ba28-390d-44a1-9eab-054ef41a1770

The sample has been transcoded to OPUS using ffmpeg n6.1.1 built with libopusenc 0.2.1-4.

It has then been tagged using Musicbrainz Picard 2.11 which results in the cover art being embedded. ffprobe describes the resulting file as follows:

```
[ogg @ 0x5a704ad78e00] 1579 bytes of comment header remain
Input #0, ogg, from 'tagged_01 The Burns We Earn.opus':
  Duration: 00:02:22.36, start: 0.000000, bitrate: 33 kb/s
  Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      MUSICBRAINZ_RELEASEGROUPID: 14a4f11e-0813-4bd3-80a6-f3b7150d63d7
[...lots of metadata left out here...]
  Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Cover (front)
```
The resulting mediafiles are attached:
[testcase_opus_coverart.zip](https://github.com/audacious-media-player/audacious/files/15377986/testcase_opus_coverart.zip)

**Describe the bug**
When opening the file `tagged_01 The Burns We Earn.opus` in Audacious 4.3.1 the cover art is not parsed and displayed. The process fails with the error `ERROR ../audacious-plugins-4.3.1/src/opus/opus.cc:142 [read_image_from_tags]: Error parsing METADATA_BLOCK_PICTURE in file:///tmp/testme/testcase/tagged_01%20The%20Burns%20We%20Earn.opus.` 

**Steps to reproduce**
See above.

**Expected behavior**
The expected result would be for the cover art to be parsed and displayed. In other audio players like e.g. VLC or Jellyfin this works.

**Additional information**
Running `opusinfo` from opus-tools 0.2 against the tagged file results in 

```
WARNING: Invalid picture parameters in METADATA_BLOCK_PICTURE comment 31 (stream 1): width (500), height (500), depth (0), and colors (0) MUST either be set to valid values or all set to 0
	METADATA_BLOCK_PICTURE=3|image/jpeg||500x500x0|<26588 bytes of image data>
```

...which indeed violates the format definition for METADATA_BLOCK_PICTURE as laid out here: https://www.opus-codec.org/docs/opusfile_api-0.6/structOpusPictureTag.html#a9af23c314edf9a995c95a4d28f49eac0

However, handling non-perfect input could be a bit more robust here and would lead to a better user experience.

**Comment by radioactiveman** [comment]
Thanks for the well written and detailed bug report. :+1: If all other would be in similar quality, life would be easier for developers...

The Audacious Opus plugin uses `opusfile` internally and its function [opus_picture_tag_parse()](https://www.opus-codec.org/docs/opusfile_api-0.6/group__header__info.html#ga6487af1d21fe87f4815567d85a27989a) for parsing the cover art.
If it says the image is invalid, we can't fix that on our side.

Please report this to the Picard developers. Creating a bug report for opusfile makes no sense in my opinion if they indeed violate the specification.

**Comment by hlinden** [comment]
Done, reported it over there: https://tickets.metabrainz.org/browse/PICARD-2909
