### ISSUE TITLE
Visualization docking no longer works

### ISSUE THREAD

**Issue by alexleduc76** [audacious-media-player/audacious#1404]
**Describe the bug**
If one of the visualizations is undocked from the main window, I can't get it to dock back to it when I drag it over the main window, which I'm pretty sure used to work a few versions back.

**Steps to reproduce**
Undock it and then try to dock it back

**Expected behavior**
It should dock. It would be nice if closing an undocked window and reopening it would open it already docked to the main window

**Additional information**
* Flatpak version 4.3.1, or native version 4.3.1-1. Qt interface
* I have the same issue with the Flatpak or Native versions
* Manjaro Linux
* KDE 6.0.5
* Wayland
* Video: https://www.youtube.com/watch?v=1NGc9t1Pj9E

On a separate note, I noticed the background for that undocked visualization window is transparent since the last update. If that's not intentional, I hope you don't fix it. It looks awesome (the window decorations were removed by me)
![Copie d'écran_20240607_221514](https://github.com/audacious-media-player/audacious/assets/13103140/5d50dd5c-54d6-405a-9c63-3897382ec9e0)

**Comment by alexleduc76** [comment]
Looks like it works fine with "env QT_QPA_PLATFORM=xcb audacious", so would this be yet another Wayland limitation for which we will get an extension after a few years aggravating of discussion?

**Comment by radioactiveman** [comment]
Yes, this looks like to be yet another limitation with Wayland. A similar issue has been discussed already [here](https://github.com/orgs/audacious-media-player/discussions/1400) for the lyrics plugin. So it affects all plugin windows, not only visualizations.

Audacious 4.4 will use XWayland by default which avoids all these types of bugs.

P.S. Great profile image! :smiley:

**Comment by alexleduc76** [comment]
Thanks, that's my dog Big Wolf 😃
