### ISSUE TITLE
make install is broken for 4.4

### ISSUE THREAD

**Issue by birdie-github** [audacious-media-player/audacious#1408]
```
./configure --prefix=/opt/audacious --disable-gtk --enable-qt5
Configuration:

  Install path:                           /opt/audacious

  D-Bus support:                          yes
  GTK support:                            no
  Qt support:                             yes
  libarchive support:                     no
  Valgrind analysis support:              no

make
make DESTDIR=/tmp/audacious install
```

Produces this:
```
ls -la /tmp/audacious/opt/audacious/lib
total 536
drwxr-xr-x. 3 root root    180 Jun 14 06:55 .
drwxr-xr-x. 6 root root    120 Jun 14 06:55 ..
lrwxrwxrwx. 1 root root     18 Jun 14 06:55 libaudcore.so -> libaudcore.so.5.5.
lrwxrwxrwx. 1 root root     18 Jun 14 06:55 libaudcore.so.5 -> libaudcore.so.5.5.
-rwxr-xr-x. 1 root root 476576 Jun 14 06:54 libaudcore.so.5.5.
lrwxrwxrwx. 1 root root     17 Jun 14 06:55 libaudtag.so -> libaudtag.so.3.0.
lrwxrwxrwx. 1 root root     17 Jun 14 06:55 libaudtag.so.3 -> libaudtag.so.3.0.
-rwxr-xr-x. 1 root root  67648 Jun 14 06:54 libaudtag.so.3.0.
drwxr-xr-x. 2 root root     60 Jun 14 06:55 pkgconfig
```

What's `libaudcore.so.5.5.` and `libaudtag.so.3.0.`?

**Comment by mschwendt** [comment]
Regression since beta1 introduced with the change to ./m4/buildsys.m4 which adds usage of an undefined ${LIB_PATCH} variable.

**Comment by radioactiveman** [comment]
@birdie-github: When creating bug reports, please use the template. Your description is unclear, the expected behavior is totally missing and the header "make install is broken" is simply nonsense.

**Comment by birdie-github** [comment]
I've given the **exact steps to reproduce the issue**.

Sorry for bothering you. Not gonna file any bug reports against Audacious from now on. Do whatever you please. I am not a fan of being spat on. This is the first time in my 20+ years of open source work that I've been blamed for absolutely unrelated trifling stuff. Template. For Christ's sake. This is just despicable.

**Comment by kaniini** [comment]
@radioactiveman I don't see what the problem is with the bug report.  The SONAMEs are being set wrong and this is a regression.

**Comment by mschwendt** [comment]
@birdie-github As a work-around, you can run "make install LIB_PATCH=0"

**Comment by radioactiveman** [comment]
> @radioactiveman I don't see what the problem is with the bug report. The SONAMEs are being set wrong and this is a regression.

And this could have been written in the bug report to make it clear. Simple as that. Same for the header. "meson install is broken" is no proper error description and gives no insights if included in a changelog.

The issue is fixed however, so let's forget it. Using Meson is the preferred way to build Audacious anyway (as mentioned in our release notes).
