### ISSUE TITLE
GTK interface: Allow to hide playlist tabs regardless of playlist count

### ISSUE THREAD

**Issue by vexillia** [audacious-media-player/audacious#1409]
**Describe the bug**
There appears to be no way of not showing playlist tabs.

**Steps to reproduce**
See screenshot below.

**Expected behavior**
When always show tabs isn't selected I expect there to be no tabs.

**Additional information**
v 4.4
Ubunutu 22.04

![Screenshot_2024-06-14_09-03-37](https://github.com/audacious-media-player/audacious/assets/23417456/0112e5d2-4763-430b-bc52-85520171546f)

**Comment by radioactiveman** [comment]
The opposite of "always show" is "not always show" but not "never show".
With the checkbox unchecked, the tabs are hidden if there is only one playlist.

What you would like to have is a tri-state `Always show`, `Auto-hide` and `Never show` like in the Qt interface.
Changing to a feature request, this is not a bug.

**Comment by radioactiveman** [comment]
Implemented with https://github.com/audacious-media-player/audacious-plugins/commit/1427488b3f6d0ef14cafb05a999e4cec11d2d42b.
