### ISSUE TITLE
Support tracklist from a separate file

### ISSUE THREAD

**Issue by gijsbers** [audacious-media-player/audacious#1419]
**Description**
For several large music files I have a tracklist in a sepate file, but there is no way I can let Audacious use it. The tracklist is a list of time offsets like `04:52` followed by a track title. I would like audacious to support a `--tracklist filename` option and also when it plays one file like `big_album_file.mp3` to look for a tracklist in `big_album_file.tracklist`. I wouldn't want to split the big album into smaller tracks.

**Comment by wildstar84** [comment]
Doesn't cuesheets (.cue) files provide this already?

**Comment by gijsbers** [comment]
Sort of yes. Didn't know about cuesheets. The documentation of audacious also doesn't mention this. The format is a bit verbose, but it works after I wrote a script to generate `.cue` files. Thanks for suggesting this!
