### ISSUE TITLE
Regression: Can't save any change of Song Info in MP3 file

### ISSUE THREAD

**Issue by rosti-il** [audacious-media-player/audacious#1421]
This is a regression in the latest 4.4 version of Audacious in the functionality that worked properly in the previous 4.3.1 version of Audacious. When I try to save any change of the **Song Info** in a local MP3 file, an error appears, as shown in the attached screenshot.

![image](https://github.com/audacious-media-player/audacious/assets/45571812/904b4b21-8642-4e38-ba6e-96f09aa51578)

My system is Windows 10 Pro 22H2 64-bit. 
Audacious 4.4 was installed by running the `audacious-4.4-win32.exe` installer after the previously installed 4.3.1 version was uninstalled.

**Comment by radioactiveman** [comment]
I could reproduce the error with Audacious 4.4 on Windows. The log inspector reveals that calling `tmpfile()` fails with the message "Permission denied". It works when running Audacious as admin (this is not recommended though).

@jlindgren90: Can you reproduce this? Since the code has not changed for years, could it be caused by the change to 64-bit?

https://github.com/audacious-media-player/audacious/blob/471a5fb7dec11e12ed6adf1f0e2db071edbfe081/src/libaudcore/vfs_local.cc#L141-L154

**Comment by jlindgren90** [comment]
It probably has something to do with the newer 64-bit MinGW platform, yes.

Possibly we need to use a different location for temporary files on Windows. I don't know when I will have time to look into the issue further.

**Comment by rosti-il** [comment]
This regression is likely related to the following bug in MinGW:
https://github.com/msys2/MINGW-packages/issues/18878

**Comment by jlindgren90** [comment]
We can probably use https://docs.gtk.org/glib/func.file_open_tmp.html instead.

**Comment by rosti-il** [comment]
Maybe the best solution would be switching from MINGW64 into UCRT64 on the MSYS2 platform when building for Windows? At least the MSYS2 project itself **[recommends](https://www.msys2.org/news/#2022-10-29-changing-the-default-environment-from-mingw64-to-ucrt64)** to use UCRT64 instead of MINGW64.

**Comment by rosti-il** [comment]
Nice!
Waiting for the next release with this fix. Is there any planned date?

**Comment by radioactiveman** [comment]
@rosti-il: Not planned yet, but I guess we can prepare a new release in the next weeks.

@jlindgren90: Do you think we can release 4.4.1 from master? Strictly speaking we have not only bug fixes there, but the other changes are mostly straightforward or backports of existing features from Qt interfaces.
