### ISSUE TITLE
File drag-and-drop does not work, warning in gdkselection-wayland.c

### ISSUE THREAD

**Issue by iquat** [audacious-media-player/audacious#1423]
**Describe the bug**
While drag-and-drop to VLC works, drag-and-drop to audacious does not work.
I tried dragging files from nautilus and nemo file managers.

**Steps to reproduce**

1. Open audacious from a terminal with the "audacious" or "audacious -G" command
2. Open a folder with at least one audio file in a file manager (e.g. nautilus or nemo)
3. Use the mouse to drag-and-drop one file from the file manager to the playlist area of audacity

**Expected behavior**
I expect that the dragged file gets added to the playlist.

**Additional information**
* Audacious version and interface: Audacious 4.3.1-2.1build2, GTK
* Operating system and version: Ubuntu 24.04
* Desktop environment: GNOME 46, Wayland
* Logs (use `LANG=C audacious -V` for English output)

(audacious:111878): Gdk-WARNING **: 10:37:49.289: ../../../gdk/wayland/gdkselection-wayland.c:283: error reading selection buffer: Operation was cancelled

[audacious-drag-n-drop.txt](https://github.com/user-attachments/files/16118588/audacious-drag-n-drop.txt)
[audacious-drag-n-drop2.txt](https://github.com/user-attachments/files/16118597/audacious-drag-n-drop2.txt)
The above two attachments might be the same, the difference is putting LANG=C before "audoacious -V".

**Comment by mschwendt** [comment]
JFTR, works here with both Audacious 4.3.1 and 4.4 (either GTK3/Qt6), GNOME Shell on Wayland and Nautilus.

**Comment by greatquux** [comment]
using the default xwayland for audacious does not exhibit this problem, only when both are on wayland (insert wayland complaint here)
