### ISSUE TITLE
Audacious can't correctly handle fonts whose name end in a number

### ISSUE THREAD

**Issue by cssobral2013** [audacious-media-player/audacious#1427]
**Describe the bug**
Audacious font misbehaves when setting as playlist or as song font any font whose name ends in space and number (in this order)

**Steps to reproduce**
 - In Audacious, set as playlist font or as song font any font whose name ends in space followed by a number (for example, Exo 2)
 - You will see below the font behaves weirdly

![Sem título2](https://github.com/audacious-media-player/audacious/assets/19995437/55614402-a50c-43b6-9630-fbf8cdce99f2)

**Expected behavior**
It should correctly display Exo 2 with its correct size

**Additional information**
* **Audacious version and interface (Qt / GTK / Winamp):** Version 4.4,  when both Qt and Winamp modes are set
* **Operating system and version:** Windows 11, version 23H2 (this appears to happen in Windows only)

**Comment by radioactiveman** [comment]
Fixed with https://github.com/audacious-media-player/audacious/commit/dff5092a48c8a1a807b9d4301680badcaa9ba762, see also #1483.

**Comment by radioactiveman** [comment]
Spoke too soon, now also fixed though with https://github.com/audacious-media-player/audacious/commit/762fd085bc64d597245fe3e8efb5701ee7d72d48.

The issue was not related to Windows by the way. It was reproducible on Linux as well.
