### ISSUE TITLE
Pop-up info is huge in 4.4 with Qt 6

### ISSUE THREAD

**Issue by sashaaaaaaaaa** [audacious-media-player/audacious#1435]
**Describe the bug**
Pop-up track information looks fine in 4.3.1 but is oversized in 4.4

**Steps to reproduce**
Just mouse over a track.

**Expected behavior**
Should be normal sized

**Additional information**
* Audacious version and interface (Qt / GTK / Winamp)
4.4 (Qt and Winamp)

* Operating system and version
Arch Linux
* Desktop environment
KDE Plasma 6.1.3
* Screenshots

Audacious 4.3.1:
![Screenshot_20240722_074521](https://github.com/user-attachments/assets/6f1d878c-20f9-4af1-b113-d70d15005966)

Audacious 4.4:
![Screenshot_20240722_074605](https://github.com/user-attachments/assets/90e4c1d0-39f4-469b-8e68-5e1457b2dd38)

**Comment by radioactiveman** [comment]
I can't reproduce this issue. There are also no related code changes between 4.3 and 4.4 for the info popup.

Are you familiar with building packages? Could you then please rebuild [audacious](https://gitlab.archlinux.org/archlinux/packaging/packages/audacious/-/tree/main) and [audacious-plugins](https://gitlab.archlinux.org/archlinux/packaging/packages/audacious-plugins) with Qt 5 support?
To do that, add the Meson option `-Dqt5=true` in the PKGBUILD `build()` function.

@jlindgren90: Can you reproduce this?

**Comment by jlindgren90** [comment]
I have not seen this.

**Comment by sashaaaaaaaaa** [comment]
I built it with Qt 5 and yeah it looks fine there. I also wanna say I tried with the default plasma theme already.

**Comment by radioactiveman** [comment]
Good to know, thanks. Adjusted the title accordingly. Is the pop-up also huge if the track has no album cover?

**Comment by mschwendt** [comment]
Qt 6 alone cannot be blamed, since the pop-ups are normal here with a Qt 6 build of Audacious. Not using KDE Plasma, though, but GNOME Shell.

**Comment by radioactiveman** [comment]
Today I have tried to reproduce this with Audacious 4.4 and the latest version of KDE Neon. It uses Plasma 6.1.3 and Qt 6.7.2. The size of the pop-up is as expected, I can't reproduce your issue. Neither with/without album cover, X11/Wayland, different scaling factors.

> Is the pop-up also huge if the track has no album cover?

Please reply @sashaaaaaaaaa.

**Comment by sashaaaaaaaaa** [comment]
I've managed to trace down the issue to my two monitors being stacked vertically. If in the monitor config I move my secondary monitor to the side instead or even below my main monitor, the issue goes away. Totally bizarre. Btw this is on X11 and the main monitor is 1080p and the secondary is 1440x900.

And yeah it happens if the track has no album cover too.

**Comment by radioactiveman** [comment]
@jlindgren90: Do you have multiple monitors and can reproduce the issue with a vertical setup? I have only one and can't help here.

**Comment by jlindgren90** [comment]
I normally use a horizontal 2-3 monitor setup and haven't seen this. I am not going to be able to look into it more at the moment, sorry.

**Comment by TheThing** [comment]
Glad I'm not the only one having this issue
![mynd](https://github.com/user-attachments/assets/ccff01ca-4654-4028-ac4f-d3517d383f85)

**Comment by mschwendt** [comment]
@TheThing So, what detail can you tell about your runtime environment?

**Comment by radioactiveman** [comment]
Fixed with https://github.com/audacious-media-player/audacious/commit/19e6b6473bd281f9f31bef3b2fb8ee0bea04b14e.

By using my TV as secondary monitor I could finally reproduce this with Qt 6, even with a standard horizontal monitor setup.

**Comment by TheThing** [comment]
My notifications are broken so I never saw your reply asking for details on the runtime environment.
But really glad you got it fixed. Once I have some free time I'll verify it by installing the git version and see if the problem is gone for good :)

**Comment by sashaaaaaaaaa** [comment]
Yeah I tried the latest commit and it's all good now 👍
