### ISSUE TITLE
elapsed time bar and lack of precision on long track(audiobooks, training, etc.)

### ISSUE THREAD

**Issue by artofit** [audacious-media-player/audacious#1438]
**Description**
v4.4 when open a long audio file, the elapsed time bar is going from 00:00:00 till end of audio.
Suppose you listen to training, audiobook, and want to re-hear a just formulated idea.
The slidder is imprecise in your choice, what you want is precision on the slider

What makes it beneficial for users?
Ease of use

PROPOSED solution
have 2 sliders:
the current one
and an additional one which would have a dynamic range from -1min to +1min from current time

Thanks
![audacious elapsed time bar - sol](https://github.com/user-attachments/assets/f7d72622-4ce5-45dd-ac54-b5166873fba4)

**Comment by radioactiveman** [comment]
You can simply use the arrow keys to jump (by default) 5 seconds forward or backward.
The time frame is even configurable in the Audacious settings window under `Advanced -> Miscellaneous -> Step backwards/forward by X seconds`.

When using the GTK interface, you can also use the `Jump to Time` dialog from the menu entry `Playback`.
And in addition GTK 3 supports a long press (for multiple seconds) on the slider to enable a "slow-mo" mode for precise adjustments.

I hope this helps. Two sliders would be overkill here and more confusing than helpful. Therefore closing.
