### ISSUE TITLE
Can PortAudio support be added?

### ISSUE THREAD

**Issue by barracuda156** [audacious-media-player/audacious#1441]
**Description**
It is desirable to have a choice of PortAudio sound output.

**Additional information**
* Do other audio players offer this feature?
Yes, `musikcube` does, for example: https://github.com/clangen/musikcube/blob/master/CMakeLists.txt

**Comment by radioactiveman** [comment]
Audacious includes enough output plugins in my opinion. Native ones for all platforms we support, as well as portable ones like SDL and QtMultimedia (which is now also compatible with Qt 6).

Adding yet another output plugin for PortAudio for limited benefits (what are they even?) and which last stable release was 3 years ago is not worth the increased maintenance burden.

Thanks anyway for suggesting this.
