### ISSUE TITLE
Copy pasting tracks in tracklist is awkward

### ISSUE THREAD

**Issue by madprops** [audacious-media-player/audacious#1444]
Audacious 4.4

If I copy a track and intend to paste it at the end of the playlist with ctrl+v , it doesn't quite happen. The song or songs are pasted above the selected track (the last track) So the last track is placed at the bottom. And if the last track is part of an album it is now separated from the album. 

I think it should paste below the selected track.

**Comment by radioactiveman** [comment]
Is `Paste at End` (Shift + CTRL + V) in the right-click context menu doing what you expect?

**Comment by madprops** [comment]
@radioactiveman ah yes that works. I didn't know about that feature.
