### ISSUE TITLE
Lower min playback speed

### ISSUE THREAD

**Issue by petarturukalo** [audacious-media-player/audacious#1447]
Is there a reason the min playback speed in the speed/pitch effect plugin is capped at 0.5? Lowering it further can help with transcribing.
![image](https://github.com/user-attachments/assets/77b92264-c3fe-40f3-b58e-8781fa4f9b95)
YouTube for instance allows a playback speed down to 0.25.
![image](https://github.com/user-attachments/assets/ccabfcf5-8017-4209-9512-d8ab0d1ea363)
The code change seems as simple as changing the value of a define, if you'd like me to put up a PR. Also if it's fine to lower it, what should the new min speed be, 0.1?

**Comment by radioactiveman** [comment]
@jlindgren90: What's your opinion on lowering the limit? It has been the same since your initial implementation with commit https://github.com/audacious-media-player/audacious-plugins/commit/d4a8b7b07c10d0e51fad28f7c405e6f4fe494d25.

**Comment by petarturukalo** [comment]
I modified the source and tested it under 0.5, and while I agree the quality does degrade, I still found it useful. Lowering it to at least 0.25 like YouTube does would be nice.

**Comment by radioactiveman** [comment]
Feel free to submit a pull request then to get the credits.

**Comment by petarturukalo** [comment]
Here's the PR https://github.com/audacious-media-player/audacious-plugins/pull/167.

**Comment by radioactiveman** [comment]
Merged as https://github.com/audacious-media-player/audacious-plugins/commit/392814fe16016b6359b163e5f7d92797d4817656, thanks.
