### ISSUE TITLE
Crash on startup: No interface plugin found

### ISSUE THREAD

**Issue by Raxelgrande** [audacious-media-player/audacious#1452]
**Describe the bug**
When i launch Audacious, it crashes. Running it from the terminal, i get the following error:

ERROR ../audacious-4.4/src/libaudcore/plugin-init.cc:155 [start_required]: No interface plugin found.
(Did you forget to install audacious-plugins?)
fish: Job 1, 'audacious' terminated by signal SIGABRT (Abort)

**Steps to reproduce**
At startup.

**Additional information**
* Audacious 4.4 (Arch Linux) QT (doesn't happen when compiling the Audacious GTK 3 from the AUR)
* Operating System: Arch Linux 6.10.5-zen1-1-zen
* Desktop environment: GNOME (Wayland)
* Logs: [Audacious Raxelgrande Logs 00.txt](https://github.com/user-attachments/files/16647189/Audacious.Raxelgrande.Logs.00.txt)

**Comment by mschwendt** [comment]
> Steps to reproduce
> At startup.

Most likely it's a miscompiled installation of Audacious and/or its plugins, since if built properly it runs fine with Qt 6 or 5 and/or GTK 3 or 2. The more suitable place to post this in would have been the "Discussion" section.

Note that while doing some trouble-shooting to figure out what you may have done wrong accidentally, you can compile with both GTK and Qt at the same time as it's possible to switch the UI at runtime and via the command-line, too.

**Comment by radioactiveman** [comment]
Have you built your own Audacious packages or do you use the official ones from the Arch repository?

**Comment by Raxelgrande** [comment]
Sorry if i was not clear enough. The problem is with the official ones provided in the Arch repository. 

Compiling the "audacious-gtk3" and "audacious-plugins-gtk3" give no issue. And i just tested to compile the "audacious-git" and the plugins and it worked.

Then, i think this issue should be closed and i shall report to the Arch packagers? Sorry for the trouble.

**Comment by radioactiveman** [comment]
I don't think Arch developers/packagers can help here.

First try with a clean configuration. So rename `~/.config/audacious/` to `audacious.bak` or similar. The official Audacious packages for Arch Linux don't enable GTK support. Maybe your configuration or app launcher (?) says to use GTK but Audacious then can't find a supported interface plugin.

**Comment by Raxelgrande** [comment]
I tried that and i had no issues, im guessing this was a configuration problem on my end. Sorry for the troubles.
