### ISSUE TITLE
Audacious closes itself when using open/add files/folder under KDE 6

### ISSUE THREAD

**Issue by ipr** [audacious-media-player/audacious#1453]
**Describe the bug**
Under KDE Plasma 6 Audacious closes itself when you use either add files or open folder dialog. The dialog opens momentarily, then both the dialog and audacious itself are closed without user interaction.

This happens on Audacious 4.3 with Qt 5 and Audacious 4.4 with Qt 6.

**Steps to reproduce**
1. start Audacious
2. select one of following from menu add files; add folder; open files; open folder
3. observe Audacious closing

**Expected behavior**
User would be able continue selecting files/folder and that progam would not close.

**Additional information**
* Qt
* Linux Debian
* KDE Plasma 6

```
INFO interface.cc:87 [interface_unload]: Unloading Qt Interface.
INFO plugin-init.cc:233 [stop_plugins]: Shutting down MPRIS 2 Server.
INFO probe-buffer.cc:30 [ProbeBuffer]: <0x5574ad19fe00> buffering enabled for /home/kaze/.config/audacious/playlists/order
INFO vfs.cc:105 [VFSFile]: <0x5574ad19fe00> open (mode r) /home/kaze/.config/audacious/playlists/order
INFO plugin-init.cc:218 [stop_plugins]: Shutting down PipeWire Output.
```

**Comment by radioactiveman** [comment]
Thanks for the bug report. This has already been reported in our forums, see https://github.com/orgs/audacious-media-player/discussions/122 for more information.

Yet I have tried to reproduce it again with KDE neon, using Plasma 6.1.4 and Qt 6.7.2. And Audacious does not close here, selecting/adding files works as intended.

So this is very likely a bug in KDE which is already fixed. Feel free to report it to them so distributions can backport the fix into their older KDE packages. And please let us know about updates in the forum thread above.

**Comment by ipr** [comment]
> Yet I have tried to reproduce it again with KDE neon, using Plasma 6.1.4 and Qt 6.7.2. And Audacious does not close here, selecting/adding files works as intended.

Thanks for information. It might be an issue of Qt 6.6 still, looking for a way to update..
