### ISSUE TITLE
Library scanning doesn't recognize .adx files even though they are supported

### ISSUE THREAD

**Issue by BlipBlerp** [audacious-media-player/audacious#1466]
**Describe the bug**
If I scan my music folder, files with the `.adx` extension won't be added to my library

**Steps to reproduce**
How and when does the bug occur?
It occurs when I try to scan a folder with an .adx file. If .adx is the only extension in a directory, a message will popup saying "No files were found in the directory". If I try to open the file it plays just as expected

**Expected behavior**
What do you expect to happen instead?
The .adx are recognized and added to my library

**Additional information**
* Audacious version and interface (Qt / GTK / Winamp)
4.4, Qt
* Operating system and version
Nobara Linux 40
* Desktop environment
KDE
* Screenshots
* Sample files
(probably can't for legal reasons)
* Logs (use `LANG=C audacious -V` for English output)

**Comment by mschwendt** [comment]
It may be that one of the input plugins' backend libraries recognizes ADX files, but none of the plugins declares that it handles files with ".adx" extension. Hence those files are not officially "supported".

Just in case, do you have the "Probe content of files with no recognized file name extension" checkbox marked in the advanced settings? Which plugin is it that recognizes those files when you add them?

**Comment by BlipBlerp** [comment]
Oh I wasn't aware of that option. Yeah enabling it works, but it will also scan my covers as songs, which is not ideal.

Regarding plugin, I am not quite sure.
![image](https://github.com/user-attachments/assets/e4320dce-676c-47de-a8ef-0bab911774f1)
Looking at that list (default plugins that came with the audacious flatpak) I guess it must be the `game console music decoder`, since adx was a format used in games

**Comment by mschwendt** [comment]
Possibly ffmpeg, since ADX is an ADPCM derivative.
Running "audacious -V yourfile.adx" would give a clue.

Activating the file detection is only a workaround. Mission objective would be to figure out which input plugin supports ADX files and then to add the ".adx" extension to the plugin's list of supported file types.

**Comment by BlipBlerp** [comment]
> Possibly ffmpeg, since ADX is an ADPCM derivative.

You were right! I ran the command as you said (only that instead of `audacious` I had to `flatpak run`) and reading through the logs it appears to cycle through the plugins until it gets to the ffmpeg/ffaudio plugin and then finds a match as such:

> INFO ../src/libaudcore/plugin-load.cc:64 [plugin_load]: Loading plugin: /app/lib/audacious/Input/ffaudio.so.
> INFO ../src/ffaudio/ffaudio-core.cc:282 [get_format_by_extension]: Matched format adx by extension.
> INFO ../src/libaudcore/probe.cc:171 [aud_file_find_decoder]: Matched FFmpeg Plugin by content.
> INFO ../src/ffaudio/ffaudio-core.cc:282 [get_format_by_extension]: Matched format adx by extension.

**Comment by radioactiveman** [comment]
> Mission objective would be to figure out which input plugin supports ADX files and then to add the ".adx" extension to the plugin's list of supported file types.

Done with https://github.com/audacious-media-player/audacious-plugins/commit/ebcad664baa82fcacd61f14032e2869c0f7bbf73. Thanks for the investigation Michael.
