### ISSUE TITLE
Pipewire output plugin prevents pipewire graph from switching to 44100 Hz

### ISSUE THREAD

**Issue by devloop0123** [audacious-media-player/audacious#1475]
**Describe the bug**
Even though Pipewire is set to allow clock rates 44100 and 48000 to prevent resampling, when playing a 44100Hz audio file with Audacious' pipewire output, the pipewire graph is run at 48000Hz which means upsampling is taking place.

If using the "pulseaudio" output of Audacious, pipewire's graph correctly runs at 44100Hz.  

**Steps to reproduce**
1. Set a custom pipewire setting in ~/.config/pipewire/pipewire.conf.d/10-rates.conf:
context.properties = {
    default.clock.allowed-rates = [ 44100 48000 ]
}
(see https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Guide-Rates#multiple-rates)
and restart the pipewire server.
2. Run Audacious with the pipewire output setting. 
3. Play a 44100 Hz audio file.
4. Run pw-top in terminal. 
5. Conclude from the description at https://docs.pipewire.org/page_man_pw-top_1.html that the output format of Audacious is 44100Hz, and the graph rate is 48000Hz, and that thus resampling occurs.
6. Change the output of Audacious to "pulseaudio", and observe that the graph's rate is now adjusted to that of Audacious' 44100 Hz, and conclude that resampling has been prevented now.

**Expected behavior**
I expect the choice of "pipewire" output to result in a 44100 Hz pipewire graph when playing 44100 Hz audio files, just as happens with th "pulseaudio" output choice.

**Additional information**
Audacious version 4.3.1 Qt 
Linux Mint 22 Cinnamon with Pipewire 1.0.5* Screenshots

**Comment by radioactiveman** [comment]
This is already fixed in Audacious 4.4 by https://github.com/audacious-media-player/audacious-plugins/commit/932e1bcb23957a283d4d6c25643cee91f54567fd.
