### ISSUE TITLE
Strip leading and trailing whitespace (symbols) for the URL open/add dialog

### ISSUE THREAD

**Issue by birdie-github** [audacious-media-player/audacious#1482]
Instead of opening `scheme://website.com/stream.m3u` you may accidentally try to open ` scheme://website.com/stream.m3u` (mind the leading space) in which case Audacious will show a very confusing message "Unknown URI scheme".

Please strip leading and trailing whitespace (that includes new lines as well). Thanks!

**Comment by radioactiveman** [comment]
That makes sense, implemented with https://github.com/audacious-media-player/audacious/commit/43e63b0f80bf7304dbd3abab605df37c13e3a33a  for GTK and https://github.com/audacious-media-player/audacious/commit/3133a14357646f92a23d43e9dd9b9d8377740371 for Qt.
