### ISSUE TITLE
4.4.1 not available on Flathub yet

### ISSUE THREAD

**Issue by NotoriousNico** [audacious-media-player/audacious#1486]
Can you please upload Audacious 4.4.1 to Flathub as well?
4.4 is still the latest version there.

**Comment by radioactiveman** [comment]
We (the Audacious developers) do not distribute Audacious via Flathub. Its community takes care of this.

Please report it here: https://github.com/flathub/org.atheme.audacious

**Comment by NotoriousNico** [comment]
Sorry, my bad.
I wasn't aware of that.
