### ISSUE TITLE
Very tiny bug in UI

### ISSUE THREAD

**Issue by Npa972** [audacious-media-player/audacious#1496]
**Describe the bug**
Audacious is so perfect :) that I can afford to report a very tiny bug.
The window closing cross is black in the dark theme in different windows.

**Steps to reproduce**
Open for example menu / files / parameters

**Expected behavior**
The window closing cross should be white in dark theme.

**Additional information**
* Audacious version and interface (Qt / GTK / Winamp) audacious-git gtk3
* Operating system and version archlinux
* Desktop environment xfce4
* Screenshots
![Capture d’écran_2024-10-20_09-44-27](https://github.com/user-attachments/assets/6f23c385-6d8a-4c38-a629-289bd48e5565)
Audacious
![Capture d’écran_2024-10-20_09-44-49](https://github.com/user-attachments/assets/29c97085-9cb3-4e14-8067-8616e2666ecf)
Other window

* Sample files
* Logs (use `LANG=C audacious -V` for English output)
* 
Thanks !

**Comment by radioactiveman** [comment]
What application is "other window"? And what icon theme do you use?

Audacious does not decide which icon theme or variant is used. So it is something we can't fix.

**Comment by Npa972** [comment]
Yes you are right, by testing other applications some have a white cross and others a black cross. This is not related to Audacious.
With apologies for the inconvenience. Thanks
I use adawaita dark an elementary icons theme

**Comment by radioactiveman** [comment]
No problem, you may report this to the elementary icons project and ask for support there.

Another difference is also that the black cross is not aligned correctly to the button label.
