### ISSUE TITLE
not reading replaygain in opus files?

### ISSUE THREAD

**Issue by zolstarym** [audacious-media-player/audacious#1500]
**Describe the bug**
I have opus music files, I ran rsgain on them, which applied a replay gain to the file. Then I play in audacious, but in the settings>audio>replaygain, I then modify "amplify untagged files" and the volume changes for the now tagged opus files, even though the files should be tagged. The file is louder than other vorbis files, so I don't think audacious is recognizing the tag, assuming rsgain did it correctly.

**Additional information**
* Audacious version and interface (Qt / GTK / Winamp)
Gtk w/ winamp
* Operating system and version
mint based on ubuntu 24.04
* Desktop environment
cinnamon
* Screenshots
* Sample files
* Logs (use `LANG=C audacious -V` for English output)
When playing the song:

INFO ../src/libaudcore/probe-buffer.cc:30 [ProbeBuffer]: <0x7643c00081b0> buffering enabled for file:///home/zol/Music/ARTIST/Barenaked%20Ladies/2021%20-%20Detour%20de%20Force/09%20-%20Bylaw.opus
INFO ../src/libaudcore/vfs.cc:105 [VFSFile]: <0x7643c00081b0> open (mode r) file:///home/zol/Music/ARTIST/Barenaked%20Ladies/2021%20-%20Detour%20de%20Force/09%20-%20Bylaw.opus
INFO ../src/libaudcore/probe-buffer.cc:50 [release_buffer]: <0x7643c00081b0> buffering disabled for file:///home/zol/Music/ARTIST/Barenaked%20Ladies/2021%20-%20Detour%20de%20Force/09%20-%20Bylaw.opus
INFO ../src/libaudcore/probe-buffer.cc:134 [fseek]: <0x7643c00081b0> buffering enabled for file:///home/zol/Music/ARTIST/Barenaked%20Ladies/2021%20-%20Detour%20de%20Force/09%20-%20Bylaw.opus
INFO ../src/libaudcore/probe-buffer.cc:50 [release_buffer]: <0x7643c00081b0> buffering disabled for file:///home/zol/Music/ARTIST/Barenaked%20Ladies/2021%20-%20Detour%20de%20Force/09%20-%20Bylaw.opus
INFO ../src/libaudcore/output.cc:270 [setup_output]: Setup output, format 0, 2 channels, 48000 Hz.

I tried modifying the amplify untagged files while playing music, but that generates no log info.

What the file should be tagged as:
Track: ./09 - Bylaw.opus
  Loudness:    -8.11 LUFS
  Peak:     1.000000 (0.00 dB)
  Gain:        -9.89 dB

**Comment by radioactiveman** [comment]
And what is your Audacious version? Audacious 4.4 reads the tags `R128_TRACK_GAIN` and `R128_ALBUM_GAIN` which is according to the spec. If `rsgain` writes other tag names, the issue lies here.

See also: https://github.com/audacious-media-player/audacious-plugins/commit/78f33f7316de481d6ce34ed3614076fda700aa1c

You can use `audacious -VV` to also enable debug output. If the tags are found, their values should be printed then.

**Comment by zolstarym** [comment]
audacious 4.4.1
I read up on rsgain, and it looks like it defaults to how everything else tags it on opus because the r128 uses a target loudness level different to the standard which causes problems with libraries of different codecs.
https://github.com/complexlogic/rsgain?tab=readme-ov-file#opus-files

Does audacious compensate for the different loudness between r128 opus and other codecs? Or perhaps there is a way it scan for both the official gain method and the tags everything else uses?

**Comment by radioactiveman** [comment]
Yes, Audacious adds 5 dB as compensation for Opus files. See the referenced commit from above. 
Please try the Opus mode "s" for rsgain to write R128_*_GAIN tags.

I think we should not change the behavior again. Audacious follows the specification while rsgain does not with the default "d" mode.

@almoped: Do you agree? You authored the commit so I would like to know your view on this.

**Comment by zolstarym** [comment]
Audacious reading the official format only sound reasonable, but since rsgain defaults to replaygain 2.0 and another tagger I found, regainer, seems to write both r128 and RG2.0, it seems like the tagger professionals seem to dislike r128, which makes me think that audacious just being able to read either will lead to a better end user experience.

**Comment by zolstarym** [comment]
> It seems possible to have Audacious work correctly with the default taggings from either Regainer, Loudgain or Rsgain, regardless of which filetype it's stored in.

Rsgain defaults to replaygain 2.0 instead of r128 for opus files though, so audacious does not work with rsgains defaults. I don't have a problem using the non default settings, I just didn't know about other taggers (rsgain is the only one being maintained it seems) or about this behavior of defaulting to RG2.0 in rsgain.

**Comment by Almoped** [comment]
As we've talked about having sample files before I did a little test. I tried to tag multiple files with Foobar2000 and Loudgain via rgbpm. All the files seems to play correctly at an adjusted gain in Audacious even though opusinfo displays this difference:

```
foobar2000.opus
User comments section follows...
	R128_TRACK_GAIN=0
Opus stream 1:
	Pre-skip: 312
	Playback gain: 20.918 dB
	Channels: 2


loudgain-rgbpm.opus
User comments section follows...
	R128_ALBUM_GAIN=5355
	R128_TRACK_GAIN=5355
Opus stream 1:
	Pre-skip: 312
	Playback gain: 0 dB
	Channels: 2
```
I will try to attach the sample files, including untagged copies. It could be useful to have the output from other taggers.

[foobar2000.zip](https://github.com/user-attachments/files/17563471/foobar2000.zip)
[loudgain.zip](https://github.com/user-attachments/files/17563472/loudgain.zip)
[untagged.zip](https://github.com/user-attachments/files/17563474/untagged.zip)

**Comment by zolstarym** [comment]
tagged with rsgain:

Processing file "rsgain_default.opus"...

New logical stream (#1, serial: 51397b8c): type opus
Encoded with libopus 1.5.2
User comments section follows...
	REPLAYGAIN_ALBUM_GAIN=26.00 dB
	REPLAYGAIN_ALBUM_PEAK=0.021667
	REPLAYGAIN_TRACK_GAIN=25.92 dB
	REPLAYGAIN_TRACK_PEAK=0.021301
Opus stream 1:
	Pre-skip: 312
	Playback gain: 0 dB
	Channels: 2
	Original sample rate: 48000 Hz
	Packet duration:   20.0ms (max),   19.9ms (avg),    5.0ms (min)
	Page duration:    300.0ms (max),  275.8ms (avg),  175.0ms (min)

	Total data length: 105488 bytes (overhead: 1.52%)
	Playback length: 0m:06.884s
	Average bitrate: 122.6 kbit/s, w/o overhead: 120.7 kbit/s
Logical stream 1 ended


[rsgain-tagged.zip](https://github.com/user-attachments/files/17563540/rsgain-tagged.zip)

**Comment by Almoped** [comment]
I have made a PR which makes RG tags work from opus files again, while keeping R128 support.

**Comment by radioactiveman** [comment]
Merged as https://github.com/audacious-media-player/audacious-plugins/commit/fd4cf4100bae2aa1e91c6d75d68fcb7493123952, thanks @Almoped for the pull request.
