### ISSUE TITLE
please respect cifs/samba shares

### ISSUE THREAD

**Issue by i300220** [audacious-media-player/audacious#1501]
On Linux (Fedora 40), I have a mount for my mp3s on my LAN defined in my fstab as /mnt/linux386/mp3.

Every program understands that. e.g. `mpg123 /mnt/linux486/mp3/Divers/Suzanne\ Vega\ -\ Luka.mp3`.

Audacious too.  The first time only!

It changes /mnt/linux486/mp3 into `uri=file:///run/user/1000/doc/143365b2/mp3/`.

That would be OK if the 143365b2 part didn't change at every reboot!  As a result I'm unable to keep any audiotheque.

Why the need to translate a perfectly understandable permanent share path into a dynamic one?

```
─────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 5 network devices                                                                                           │
├───────────────────────┬────────┬────────┬───────┬───────────────────────────────┬──────┬────────────────────┤
│ MOUNTED ON            │   SIZE │   USED │ AVAIL │              USE%             │ TYPE │ FILESYSTEM         │
├───────────────────────┼────────┼────────┼───────┼───────────────────────────────┼──────┼────────────────────┤
│ /mnt/linux486/mp3     │  28.1G │  23.4G │  4.6G │ [################....]  83.5% │ cifs │ //linux486/mp3     │
│ /mnt/linux486/mythtv  │ 216.6G │ 156.2G │ 60.4G │ [##############......]  72.1% │ cifs │ //linux486/mythtv  │
│ /mnt/linux486/shizuma │ 113.2G │  71.0G │ 42.2G │ [############........]  62.7% │ cifs │ //linux486/shizuma │
│ /mnt/linux486/tmp     │ 113.2G │  71.0G │ 42.2G │ [############........]  62.7% │ cifs │ //linux486/tmp     │
│ /mnt/linux486/web     │ 113.2G │  71.0G │ 42.2G │ [############........]  62.7% │ cifs │ //linux486/web     │
╰───────────────────────┴────────┴────────┴───────┴───────────────────────────────┴──────┴────────────────────╯

```
![Capture d’écran du 2024-10-23 15-59-34](https://github.com/user-attachments/assets/f35b8761-a199-4622-95f1-6865920a1882)

![Capture d’écran du 2024-10-23 16-00-47](https://github.com/user-attachments/assets/896628ee-3e2d-4b39-8889-d576962af788)

**Comment by mschwendt** [comment]
Unusual, but looks like it's magic coming from XDG Portal services.
( systemctl --user status xdg-document-portal.service )

**Comment by i300220** [comment]
> Unusual, but looks like it's magic coming from XDG Portal services. ( systemctl --user status xdg-document-portal.service )

Nice catch!

Removed audacious flatpak and installed Fedora 40 version to fix this.

Thanks a lot!

**Comment by radioactiveman** [comment]
The Flatpak version also explains the unusual config path under `~/.var/app/org.atheme.org/`.

Closing then and Kudos to Michael.
