### ISSUE TITLE
Failed to load module "atk-bridge": 'gtk_module_display_init': - undefined symbol: gtk_module_display_init; Unable to locate theme engine in module_path: "adwaita",

### ISSUE THREAD

**Issue by slrslr** [audacious-media-player/audacious#1511]
**Describe the bug**
$ audacious &
```
[1] 31632
$ eGtk-Message: 07:00:24.795: Failed to load module "atk-bridge": 'gtk_module_display_init': /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libgail.so: undefined symbol: gtk_module_display_init
x
(audacious:31632): Gtk-WARNING **: 07:00:24.996: Unable to locate theme engine in module_path: "adwaita",
```

$ apt search libgail
```
Sorting... Done
Full Text Search... Done
libgail-3-0/stable,now 3.24.38-2~deb12u3 amd64 [installed,automatic]
  GNOME Accessibility Implementation Library -- shared libraries

libgail-3-dev/stable 3.24.38-2~deb12u3 amd64
  GNOME Accessibility Implementation Library -- development files

libgail-3-doc/stable,stable 3.24.38-2~deb12u3 all
  documentation files of the Gail library

libgail-common/stable,now 2.24.33-2+deb12u1 amd64 [installed,automatic]
  GNOME Accessibility Implementation Library -- common modules

libgail-dev/stable 2.24.33-2+deb12u1 amd64
  GNOME Accessibility Implementation Library -- development files

libgail-doc/stable,stable 2.24.33-2+deb12u1 all
  documentation files of the Gail library

libgail18/stable,now 2.24.33-2+deb12u1 amd64 [installed,automatic]
  GNOME Accessibility Implementation Library -- shared libraries
```

**Additional information**
* Audacious 4.2 (Debian package) - Version: 4.2-1 GTK (legacy) mode, GTK UI
* Debian 12 (stable, bookworm) 6.1.0-27-amd64
* Operating System: Debian GNU/Linux 12
* KDE Plasma Version: 5.27.5
* KDE Frameworks Version: 5.103.0
* Qt Version: 5.15.8
* Graphics Platform: X11

**Comment by radioactiveman** [comment]
This is not an Audacious issue. I assume other GTK 3 applications will behave the same, right?
Have you tried (re)installing `libatk-adaptor` and `gnome-themes-extra`?

If it doesn't help, please ask in a Debian specific forum for further suggestions.

- https://stackoverflow.com/questions/75406844/not-loading-module-atk-bridge-the-functionality-is-provided-by-gtk-natively
- https://askubuntu.com/questions/774664/gtk-warning-unable-to-locate-theme-engine-in-module-path-adwaita-error-o

**Comment by slrslr** [comment]
Thanks, It WORKED.

To get rid of the atk-bridge failure: `sudo apt reinstall libatk-adaptor`
Before it, it was like this: libatk-adaptor/stable 2.46.0-5 amd64 [residual-config] (Priority: optional)

gnome-themes-extra was NOT installed, and was "Priority: optional" with a description "Adwaita, the standard GNOME theme, for the GTK 2.x toolkit. The GTK 3.x version is already included in libgtk-3-0."
And I had that libgtk 3 already installed.

After running "sudo apt install gnome-themes-extra" the adwaita warning/error also disappeared, so all good.

While Audacious is installed from official repo.: audacious/stable,now 4.2-1 amd64 [installed]
I should notify Debian maintainer so he includes these packages as a dependencies and when Audacious is updated, the dependencies will be automatically removed uninstalled (not in my case, it will forever use disk space since I have manually installed these)?

**Comment by radioactiveman** [comment]
Glad it helped, closing then.

On Debian Audacious 4.2 still uses GTK 2, later versions then use GTK 3. If you configured your system to use the Adwaita theme, you need to install it separately for GTK 2. I don't think it is a packaging issue on Debian side. And especially not for the Audacious package since any other GTK 2 application would have the same issue.

Feel free though to contact the Debian package maintainers about this.
