### ISSUE TITLE
Porting to Adwaita and GTK4

### ISSUE THREAD

**Issue by vovagorodok** [audacious-media-player/audacious#1514]
Audacious is the most functional player on Linux, and I can't find better alternative. That's why I use it all the time. Unfortunately the UI looks a bit outdated in the current Gnome. There are plans to use Adwaita?

**Comment by regs01** [comment]
libadwaita is ugly, dull and boring. Better stay with theming.

**Comment by vovagorodok** [comment]
I understand Your PoV, it can be boring. But I am one of those who like consistency of programs with the OS. I would prefer to have that option if it possible

**Comment by regs01** [comment]
Just have own theme with own consistency without enforcing other on what you like.

**Comment by vovagorodok** [comment]
Ideally, when application try to be as consistent as possible with DE, regardless of whether it is KDE Plasma, Gnome or Windows (with considering of Light/Dark switching). And with ability to customize it as user prefer.

Thank you, I understood your point of view. I am still curious about the application authors thoughts

**Comment by Fr-Dae** [comment]
Here my 2cents contribution, arc, arc-dark and clearlook with oxygen icon it's look like very good
don't know if that can help (i use GTK winamp-refugee) theme
