### ISSUE TITLE
Playback stops intermittently within 1 second

### ISSUE THREAD

**Issue by pumaelbusta** [audacious-media-player/audacious#1526]
**Describe the bug**
Playback stops intermittently within 1 second after pressing play, or seeking.

**Steps to reproduce**
I couldn't find a pattern of the occurrence, but it is happening right after play or seek. When it doesn't happen, playback goes forward seamlessly. When it happens, the time indicator stops too, while it seems keep in play mode. If I press pause then it switches to pause and even back to play, but not playing. Usually doing a seek makes playback go as expected on first try.
It happens also when playing FLAC or mp3.

**Expected behavior**
Playback should not stop.

**Additional information**
Sometimes I get this in cli, but seems to be unrelated (doesn't concur with the playback stop, and no symptom experienced when this error appears)
ERROR alsa.cc:253 [get_delay_locked]: snd_pcm_recover failed: Input/output error.

* Audacious version and interface:
(Qt / GTK / Winamp) : 4.1/Winamp, 4.4 Qt/GTK/Winamp

* Operating system and version 
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="KDE neon 6.0"
PRETTY_NAME="KDE neon 6.1"
NAME="KDE neon"
VERSION_ID="22.04"

* Desktop environment
KDE on X11
* Screenshots
![Screenshot_20241125_203054](https://github.com/user-attachments/assets/b5c11e96-f82f-4fd3-971d-5ae8ec69850e)
![Screenshot_20241125_203328](https://github.com/user-attachments/assets/514fdeef-4377-4c2f-ba56-4f1b6dd01dd1)

* Sample files
* Logs (use `LANG=C audacious -V` for
[audacious_output.txt](https://github.com/user-attachments/files/17908174/audacious_output.txt)
 English output)

**Comment by radioactiveman** [comment]
You use ALSA as output plugin, right? How does PulseAudio or PipeWire behave on your system?

@jlindgren90: What would you suggest in this case? Should it be reported to the ALSA developers instead?

**Comment by pumaelbusta** [comment]
> You use ALSA as output plugin, right? How does PulseAudio or PipeWire behave on your system?
> 
> @jlindgren90: What would you suggest in this case? Should it be reported to the ALSA developers instead?

Well, my bad - I didn't even try with other output plugin. Seems not happening on Pulse (I don't see Pipewire as an option, I'm after a system upgrade that possibly restored Pulse for me and I didn't notice it yet). Me personally doesn't care about alsa so if you don't mind it can be closed.

**Comment by radioactiveman** [comment]
OK, closing then. :+1:
