### ISSUE TITLE
Issue with building audacious-plugins using MacPorts: constexpr function never produces a constant expression [-Winvalid-constexpr]

### ISSUE THREAD

**Issue by punkcakez13** [audacious-media-player/audacious#1528]
I'm trying to install Audacious on MacOS 10.15.7 Catalina using MacPorts' (V2.10.5) port. When building audacious-plugins v4.4.2 I get:
`--->  Building audacious-plugins
Error: Failed to build audacious-plugins: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_audacious-plugins/audacious-plugins/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there
is a bug.
Error: Processing of port audacious failed`

Looking at the log file:
`In file included from ../audacious-plugins-4.4.2/src/background_music/background_music.cc:19:
In file included from ../audacious-plugins-4.4.2/src/background_music/FrameBasedEffectPlugin.h:21:
In file included from ../audacious-plugins-4.4.2/src/background_music/LoudnessFrameProcessor.h:22:
../audacious-plugins-4.4.2/src/background_music/Loudness.h:46:28: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
    static constexpr float get_weight(const float seconds)
                           ^
../audacious-plugins-4.4.2/src/background_music/Loudness.h:51:16: note: non-constexpr function 'powf' cannot be used in a constant expression
        return powf(relative, perception_weight_power);
               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/math.h:428:14: note: declared here
extern float powf(float, float);
             ^
1 error generated.`

**Comment by radioactiveman** [comment]
What compiler and version do you use? Is this change fixing the error?

CC: @emmef

```diff
diff --git a/src/background_music/Loudness.h b/src/background_music/Loudness.h
index 503f2c9d5..cc9c5eb3a 100644
--- a/src/background_music/Loudness.h
+++ b/src/background_music/Loudness.h
@@ -43,7 +43,7 @@ struct Loudness
         float weight = 0;
     };
 
-    static constexpr float get_weight(const float seconds)
+    static float get_weight(const float seconds)
     {
         const float relative = aud::clamp(seconds, perception_peak_seconds,
                                           perception_center_seconds) /
```

**Comment by punkcakez13** [comment]
It looks it compiled successfully from source editing Loudness.h. Idk if it's an issue with MacPorts' port or with the source code, anyways now it's fixed. tysm

**Comment by radioactiveman** [comment]
Fixed with https://github.com/audacious-media-player/audacious-plugins/commit/c1c7bc6f0ba89e22a85bdfad9ad53c621fb23756, thanks for reporting.
