### ISSUE TITLE
Nonexistent tray icon

### ISSUE THREAD

**Issue by stemy2** [audacious-media-player/audacious#907]
### Discussed in https://github.com/orgs/audacious-media-player/discussions/906

<div type='discussions-op-text'>

<sup>Originally posted by **stemy2** April 24, 2024</sup>
Hello,

I enabled the tray icon, but it's not visible. If i close the app or open directly an audio file, the music is (still) playing but is not visible in the notifications zone.</div>

**Comment by jlindgren90** [comment]
No need to have both a discussion and an issue. Please continue the discussion at #906. Thanks!
